# Generated by Django 4.2.7 on 2026-04-22 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_propertyimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PropertyImage",
        ),
    ]
