# Generated by Django 4.2.7 on 2026-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_add_images_and_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='gouvernement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
